# docker-compose.yml for malice.io site
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - docs
    restart: always
    environment:
      DOMAINS: 'localhost-> http://docs:443'
      STAGE: 'local'

  docs:
    image: malice/docs
    restart: always
    environment:
      MALICE_DOCS_THEME: "hugo-material-docs"
      MALICE_DOCS_URL: "localhost"
      MALICE_DOCS_PORT: 443
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
