# docker-compose.yml for malice.io site
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      # - docs
      - wordpress
    restart: always
    environment:
      DOMAINS: 'malice.io-> http://wordpress, docs.malice.io-> http://docs'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

  docs:
    image: malice/docs
    restart: always
    environment:
      MALICE_DOCS_THEME: "hugo-material-docs"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  wordpress:
    image: wordpress
    links:
      - db:mysql
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD

  db:
    image: mariadb
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

volumes:
  data:
