# docker-compose.yml for my_wordpress site

nginx-acme:
  image: steveltn/nginx-acme
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  environment:
    - "DOMAINS=malice.io -> http://wordpress"
    - "PRODUCTION=true"

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: hrJFWLDjknNzZE6LgwR6stGLzRBRCyCPrwWYwaJdNnTzRCt9Cp
