# docker-compose.yml for my_wordpress site

https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  links:
    - wordpress
  restart: always
  environment:
    DOMAINS: 'malice.io-> http://wordpress'
    STAGE: 'production'
    FORCE_RENEW: 'true'

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: hrJFWLDjknNzZE6LgwR6stGLzRBRCyCPrwWYwaJdNnTzRCt9Cp
